### ISSUE TITLE
Repliage sur le bouton « Dérouler »

### ISSUE THREAD

**Issue by lanodan** [mrtino/2019#2]
Le bouton dérouler permet d’afficher les informations (longues) mais il y a besoin de les faire défiller pour atteindre « Fermer ».

Je pense que le bouton « Dérouler » peut aussi se changer en bouton « Fermer ».

**Comment by salut-c-leo** [comment]
C'est vrai, la question est comment implémenter ça. En faisant apparaître un bouton Fermer à côté ? En changeant la fonction du bouton quand on appuie sur Dérouler ?
J'ai pas vraiment d'idée sur comment régler le problème, mais si tu as le temps de trouver une solution, ce serait vraiment sympa.

**Comment by salut-c-leo** [comment]
J'ai trouvé une solution avec https://github.com/mrtino/2019/commit/2920b5c6845cafb0a37e8b8e0efe2d39a75edd97, c'est assez flemmard mais c'est efficace.

**Comment by lanodan** [comment]
J’ai pas trop le temps de regarder le code (surtout que je suis plutôt backend) mais avoir un bouton genre spoiler/CW serait mieux je pense, donc changer la fonction.

**Comment by salut-c-leo** [comment]
Corrigé avec #3
