### ISSUE TITLE
Les Anglais participent au vote

### ISSUE THREAD

**Issue by nils-van-zuijlen** [mrtino/2019#6]
Donc la France n'a "que" 74 places et pas 79.

**Comment by salut-c-leo** [comment]
Encore confirmé ce matin que [79 candidat·e·s sont à élire](https://www.lemonde.fr/politique/article/2019/05/13/europeennes-spots-televises-professions-de-foi-la-campagne-officielle-a-commence_5461400_823448.html), le ministère de l'Intérieur a enregistré 79 noms pour chaque liste, je ne vois pas pourquoi il reviendrait sur sa décision.
